// Mobile (390px) checks: node tools/mobile.mjs
import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
const shot = (n) => page.screenshot({ path: `reference/mine/m_${n}.png` });
await page.goto('http://localhost:5303/#/project/meridian-portal/overview', { waitUntil: 'networkidle' });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: 'networkidle' });
await shot('1_overview');
await page.evaluate(() => document.querySelector('.scroll').scrollTo(0, 600));
await shot('2_overview_scrolled');
console.log('page width', await page.evaluate(() => [document.documentElement.scrollWidth, document.querySelector('.scroll').scrollWidth]));
await page.getByRole('button', { name: 'Open sidebar' }).click();
await page.waitForTimeout(300);
await shot('3_drawer');
await page.locator('.sidebar a', { hasText: 'Initiatives' }).first().click();
await page.waitForTimeout(300);
await shot('4_initiatives');
await page.locator('.health-cell').nth(2).click();
await page.waitForTimeout(200);
await shot('5_popover');
await page.keyboard.press('Escape');
await page.goto('http://localhost:5303/#/pulse', { waitUntil: 'networkidle' });
await shot('6_pulse');
await page.goto('http://localhost:5303/#/project/harbor-shop/updates', { waitUntil: 'networkidle' });
await page.locator('.latest-empty').click();
await shot('7_composer');
console.log(errors.length ? errors.join('\n') : 'no errors');
await browser.close();
